# ---- Build Stage ----
FROM node:24-alpine3.21 AS builder

WORKDIR /app

COPY package*.json tsconfig.json ./
RUN npm install --legacy-peer-deps

COPY src ./src
# Added tsc to build backend
RUN npx tsc  # build backend

# ---- Runtime Stage ----
FROM node:24-alpine3.21 AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY package*.json ./

EXPOSE 4000

CMD ["node", "dist/server.js"]
